version: '3.8'

services:
  postgresdb:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 2s
      timeout: 5s
      retries: 10

  app:
    image: borchowiec/mentoring-api:1.0.0
    ports:
      - '3000:3000'
    environment:
      POSTGRES_URL: postgresql://postgres:postgres@postgresdb:5432/postgres
    depends_on:
      postgresdb:
        condition: service_healthy

frontend:
  build:
    context: ./frontend
    dockerfile: Dockerfile
  ports:
    - '5173:80'
  environment:
    VITE_API_URL: http://app:3000/api/v1
  depends_on:
    app:
      condition: service_started
